// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEIabPpcCpEjlb-K2_QJPQ73kFYTOzio',
    appId: '1:853447844228:web:df8982ad51f665bebd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    authDomain: 'frit-hub.firebaseapp.com',
    storageBucket: 'frit-hub.firebasestorage.app',
    measurementId: 'G-M8FLLNJ5KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ymocfJAyNsoHIkxsNvKg6VPn59tsZhM',
    appId: '1:853447844228:android:feed00ac05ff9911bd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxctKyfB2zZjdfXMdvFQjg_eV-wbBLClA',
    appId: '1:853447844228:ios:654812f1525eb88fbd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxctKyfB2zZjdfXMdvFQjg_eV-wbBLClA',
    appId: '1:853447844228:ios:654812f1525eb88fbd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGEIabPpcCpEjlb-K2_QJPQ73kFYTOzio',
    appId: '1:853447844228:web:69a2700a6b73f78fbd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    authDomain: 'frit-hub.firebaseapp.com',
    storageBucket: 'frit-hub.firebasestorage.app',
    measurementId: 'G-1Z0LRRP82D',
  );
}
